update git and snapshots

diff --git a/.github/workflows/get_ncbi_ena_tolids_daily.yml b/.github/workflows/get_ncbi_ena_tolids_daily.yml
--- a/.github/workflows/get_ncbi_ena_tolids_daily.yml
+++ b/.github/workflows/get_ncbi_ena_tolids_daily.yml
@@ -15,37 +15,38 @@ jobs:
       - name: Get dockers
         run:  docker pull genomehubs/genomehubs:latest
 
-  get-ncbi-datasets:
-    needs:
-      - pull-docker
-    runs-on:  self-hosted
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-      - name: Download NCBI datasets executable
-        run: |
-          curl https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/LATEST/linux-amd64/datasets > datasets
-          chmod a+x datasets
-      - name: Download NCBI eukaryota datasets zip
-        run: |
-          mkdir -p sources/assembly-data
-          ./datasets download genome taxon "Eukaryota" --dehydrated --filename sources/assembly-data/eukaryota.zip
-          unzip -o -d sources/assembly-data sources/assembly-data/eukaryota.zip ncbi_dataset/data/assembly_data_report.jsonl
-      - name: Run docker genomehubs parse --ncbi-datasets
-        run: |
-          docker run --rm --network=host \
-            -v `pwd`/sources:/genomehubs/sources \
-            genomehubs/genomehubs:latest bash -c \
-            "genomehubs parse --ncbi-datasets sources/assembly-data --outfile sources/assembly-data/ncbi_datasets_eukaryota.tsv.gz"
-      - name: Clean up expanded zip
-        run: |
-            rm -rf sources/assembly-data/ncbi_dataset datasets
-      - name: Commit changes if needed
-        uses: stefanzweifel/git-auto-commit-action@v4
+  # get-ncbi-datasets:
+  #   needs:
+  #     - pull-docker
+  #   runs-on:  self-hosted
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v2
+  #     - name: Download NCBI datasets executable
+  #       run: |
+  #         curl https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/LATEST/linux-amd64/datasets > datasets
+  #         chmod a+x datasets
+  #     - name: Download NCBI eukaryota datasets zip
+  #       run: |
+  #         mkdir -p sources/assembly-data
+  #         ./datasets download genome taxon "Eukaryota" --dehydrated --filename sources/assembly-data/eukaryota.zip
+  #         unzip -o -d sources/assembly-data sources/assembly-data/eukaryota.zip ncbi_dataset/data/assembly_data_report.jsonl
+  #     - name: Run docker genomehubs parse --ncbi-datasets
+  #       run: |
+  #         docker run --rm --network=host \
+  #           -v `pwd`/sources:/genomehubs/sources \
+  #           genomehubs/genomehubs:latest bash -c \
+  #           "genomehubs parse --ncbi-datasets sources/assembly-data --outfile sources/assembly-data/ncbi_datasets_eukaryota.tsv.gz"
+  #     - name: Clean up expanded zip
+  #       run: |
+  #           rm -rf sources/assembly-data/ncbi_dataset datasets
+  #     - name: Commit changes if needed
+  #       uses: stefanzweifel/git-auto-commit-action@v4
 
   get-refseq-organelles:
     needs:
-      - get-ncbi-datasets
+      # - get-ncbi-datasets
+      - pull-docker
     runs-on:  self-hosted
     steps:
       - name: Checkout
@@ -57,7 +58,10 @@ jobs:
             genomehubs/genomehubs:latest bash -c \
             "genomehubs parse --refseq-organelles --outfile sources/assembly-data/refseq_organelles.tsv.gz"
       - name: Commit changes if needed
-        uses: stefanzweifel/git-auto-commit-action@v4
+        run:  |
+          git add sources
+          git commit -m 'update sources'
+          git push || exit 0
 
   get-ena-taxonomy-extra:
     needs:
@@ -77,7 +81,10 @@ jobs:
             ena-taxonomy.extra.curr.jsonl
           cd ../../
       - name: Commit changes if needed
-        uses: stefanzweifel/git-auto-commit-action@v4
+        run:  |
+          git add sources
+          git commit -m 'update sources'
+          git push || exit 0
 
   get-tolids:
     needs:
@@ -89,9 +96,10 @@ jobs:
       - name: Get latest tolids
         run:  |
           mkdir -p sources/tolids
-          cd sources/tolids
           curl -s https://gitlab.com/wtsi-grit/darwin-tree-of-life-sample-naming/-/raw/master/tolids.txt \
           | gzip -c > sources/tolids/tolids.tsv.gz
-          cd ../../
       - name: Commit changes if needed
-        uses: stefanzweifel/git-auto-commit-action@v4
+        run:  |
+          git add sources
+          git commit -m 'update sources'
+          git push || exit 0
