comment for partial run

diff --git a/.github/workflows/new_release.yml b/.github/workflows/new_release.yml
--- a/.github/workflows/new_release.yml
+++ b/.github/workflows/new_release.yml
@@ -17,7 +17,7 @@ jobs:
   update_ncbi_ena_tolids:
     needs:
       - get_dockers
-    runs-on:  self-hosted
+    runs-on:  [ self-hosted, runner1 ]
     steps:
       - uses: actions/checkout@v3
         with:
@@ -28,62 +28,62 @@ jobs:
       - name: Create a new branch
         run:  |
           git checkout -b $RELEASE
-      - name: Download NCBI datasets executable
-        run: |
-          curl https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/LATEST/linux-amd64/datasets > datasets
-          chmod a+x datasets
-          sudo ip link set ens3 mtu 1500
-      - name: Download NCBI eukaryota datasets zip
-        run: |
-          mkdir -p sources/assembly-data
-          ./datasets download genome taxon "Eukaryota" --no-progressbar --dehydrated --filename sources/assembly-data/eukaryota.zip
-          unzip -o -d sources/assembly-data sources/assembly-data/eukaryota.zip ncbi_dataset/data/assembly_data_report.jsonl
-      - name: Run docker genomehubs parse --ncbi-datasets
-        run: |
-          docker run --rm --network=host \
-            -v `pwd`/sources:/genomehubs/sources \
-            genomehubs/genomehubs:develop bash -c \
-            "genomehubs parse --ncbi-datasets sources/assembly-data --outfile sources/assembly-data/ncbi_datasets_eukaryota.tsv.gz"
-          cp sources/assembly-data/ncbi_datasets_eukaryota.tsv.gz sources/assembly-data-taxon/ncbi_datasets_eukaryota.tsv.gz
-      - name: Clean up expanded ncbi datasets zip
-        run:  rm -rf sources/assembly-data/ncbi_dataset datasets
-      - name: Run docker genomehubs parse --refseq-organelles
-        run: |
-          docker run --rm --network=host \
-            -v `pwd`/sources:/genomehubs/sources \
-            genomehubs/genomehubs:develop bash -c \
-            "genomehubs parse --refseq-organelles --outfile sources/assembly-data/refseq_organelles.tsv.gz"
-      - name: Get extra ENA taxonomy nodes
-        run:  |
-          mkdir -p sources/ena-taxonomy
-          cd sources/ena-taxonomy
-          bash ../../scripts/get_ena_taxonomy_extra.bash
-          rm -f ena-taxonomy.extra.jsonl ena-taxonomy.xml.taxids \
-            resulttaxon.tax_tree2759.tsv ena-taxonomy.extra.prev.jsonl \
-            ena-taxonomy.extra.prev.taxids resulttaxon.tax_tree2759.extra.curr.tsv \
-            ena-taxonomy.extra.curr.jsonl
-          cd ../../
-      - name: Get latest tolids
-        run:  |
-          mkdir -p sources/tolids
-          curl -s https://gitlab.com/wtsi-grit/darwin-tree-of-life-sample-naming/-/raw/master/tolids.txt \
-          | gzip -c > sources/tolids/tolids.tsv.gz
+      # - name: Download NCBI datasets executable
+      #   run: |
+      #     curl https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/LATEST/linux-amd64/datasets > datasets
+      #     chmod a+x datasets
+      #     sudo ip link set ens3 mtu 1500
+      # - name: Download NCBI eukaryota datasets zip
+      #   run: |
+      #     mkdir -p sources/assembly-data
+      #     ./datasets download genome taxon "Eukaryota" --no-progressbar --dehydrated --filename sources/assembly-data/eukaryota.zip
+      #     unzip -o -d sources/assembly-data sources/assembly-data/eukaryota.zip ncbi_dataset/data/assembly_data_report.jsonl
+      # - name: Run docker genomehubs parse --ncbi-datasets
+      #   run: |
+      #     docker run --rm --network=host \
+      #       -v `pwd`/sources:/genomehubs/sources \
+      #       genomehubs/genomehubs:develop bash -c \
+      #       "genomehubs parse --ncbi-datasets sources/assembly-data --outfile sources/assembly-data/ncbi_datasets_eukaryota.tsv.gz"
+      #     cp sources/assembly-data/ncbi_datasets_eukaryota.tsv.gz sources/assembly-data-taxon/ncbi_datasets_eukaryota.tsv.gz
+      # - name: Clean up expanded ncbi datasets zip
+      #   run:  rm -rf sources/assembly-data/ncbi_dataset datasets
+      # - name: Run docker genomehubs parse --refseq-organelles
+      #   run: |
+      #     docker run --rm --network=host \
+      #       -v `pwd`/sources:/genomehubs/sources \
+      #       genomehubs/genomehubs:develop bash -c \
+      #       "genomehubs parse --refseq-organelles --outfile sources/assembly-data/refseq_organelles.tsv.gz"
+      # - name: Get extra ENA taxonomy nodes
+      #   run:  |
+      #     mkdir -p sources/ena-taxonomy
+      #     cd sources/ena-taxonomy
+      #     bash ../../scripts/get_ena_taxonomy_extra.bash
+      #     rm -f ena-taxonomy.extra.jsonl ena-taxonomy.xml.taxids \
+      #       resulttaxon.tax_tree2759.tsv ena-taxonomy.extra.prev.jsonl \
+      #       ena-taxonomy.extra.prev.taxids resulttaxon.tax_tree2759.extra.curr.tsv \
+      #       ena-taxonomy.extra.curr.jsonl
+      #     cd ../../
+      # - name: Get latest tolids
+      #   run:  |
+      #     mkdir -p sources/tolids
+      #     curl -s https://gitlab.com/wtsi-grit/darwin-tree-of-life-sample-naming/-/raw/master/tolids.txt \
+      #     | gzip -c > sources/tolids/tolids.tsv.gz
 
-      - name: Update sources/goat.yaml
-        run:  |
-          perl -i -plne 's/20\d\d\.\d\d.\d\d/'$RELEASE'/g' sources/goat.yaml
+      # - name: Update sources/goat.yaml
+      #   run:  |
+      #     perl -i -plne 's/20\d\d\.\d\d.\d\d/'$RELEASE'/g' sources/goat.yaml
 
-      - name: Commit files in branch
-        run: |
-          git config --local user.email "sujaikumar@gmail.com"
-          git config --local user.name "sujaikumar"
-          git add -A
-          git commit -m "Add changes from update_ncbi_ena_tolids"
-      - name: Push changes
-        uses: ad-m/github-push-action@master
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          branch: ${{ env.RELEASE }}
+      # - name: Commit files in branch
+      #   run: |
+      #     git config --local user.email "sujaikumar@gmail.com"
+      #     git config --local user.name "sujaikumar"
+      #     git add -A
+      #     git commit -m "Add changes from update_ncbi_ena_tolids"
+      # - name: Push changes
+      #   uses: ad-m/github-push-action@master
+      #   with:
+      #     github_token: ${{ secrets.GITHUB_TOKEN }}
+      #     branch: ${{ env.RELEASE }}
 
   genomehubs_init:
     needs:
@@ -101,62 +101,62 @@ jobs:
           fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
           ref: ${{ env.RELEASE }}
 
-      - name: Check es health
-        run:  curl -s "http://es1:9200/_cat/health"
+      # - name: Check es health
+      #   run:  curl -s "http://es1:9200/_cat/health"
 
-      - name: Create dev snapshot repo if it doesn't exist
-        run: |
-          curl -s -X PUT "es1:9200/_snapshot/dev" \
-            -H 'Content-Type: application/json' \
-            -d' { "type": "fs", "settings": { "location": "/usr/share/elasticsearch/snapshots/dev" } }' || exit 0
+      # - name: Create dev snapshot repo if it doesn't exist
+      #   run: |
+      #     curl -s -X PUT "es1:9200/_snapshot/dev" \
+      #       -H 'Content-Type: application/json' \
+      #       -d' { "type": "fs", "settings": { "location": "/usr/share/elasticsearch/snapshots/dev" } }' || exit 0
 
-      - name: Create production-RELEASE snapshot repo if it doesn't exist
-        run: |
-          curl -s -X PUT "es1:9200/_snapshot/production-$RELEASE" \
-            -H 'Content-Type: application/json' \
-            -d' { "type": "fs", "settings": { "location": "/usr/share/elasticsearch/snapshots/production/production-'$RELEASE'" } }' || exit 0
+      # - name: Create production-RELEASE snapshot repo if it doesn't exist
+      #   run: |
+      #     curl -s -X PUT "es1:9200/_snapshot/production-$RELEASE" \
+      #       -H 'Content-Type: application/json' \
+      #       -d' { "type": "fs", "settings": { "location": "/usr/share/elasticsearch/snapshots/production/production-'$RELEASE'" } }' || exit 0
 
-      - name: Clean taxdump folder and delete indices and snapshots for that release
-        run: |
-          mkdir -p resources/taxdump
-          rm -rf resources/taxdump/*
-          curl -s -X DELETE "es1:9200/*"
-          curl -s -X DELETE "es1:9200/_snapshot/dev/*"
-      - name: Run genomehubs init
-        run: |
-          docker run --rm --network=host \
-            -v `pwd`/sources:/genomehubs/sources \
-            -v /volumes/docker/resources:/genomehubs/resources \
-            genomehubs/genomehubs:develop bash -c \
-              "genomehubs init \
-                --es-host http://es1:9200 \
-                --taxonomy-source ncbi \
-                --config-file sources/goat.yaml \
-                --taxonomy-jsonl sources/ena-taxonomy/ena-taxonomy.extra.jsonl.gz \
-                --taxonomy-ncbi-root 2759 \
-                --taxon-preload"
-      - name: Run docker genomehubs index --assembly-data
-        run: |
-          docker run --rm --network=host \
-            -v `pwd`/sources:/genomehubs/sources \
-            genomehubs/genomehubs:develop bash -c \
-              "genomehubs index \
-                --es-host http://es1:9200 \
-                --taxonomy-source ncbi \
-                --config-file sources/goat.yaml \
-                --assembly-dir sources/assembly-data"
-      - name: Snapshot initassembly
-        run: |
-          curl -s -X DELETE "es1:9200/_snapshot/dev/${RELEASE}_initassembly" || exit 0
-          curl -s -X PUT    "es1:9200/_snapshot/dev/${RELEASE}_initassembly?wait_for_completion=true&pretty" \
-            -H 'Content-Type: application/json' \
-            -d' { "indices": "assembly*,attributes*,feature*,identifiers*,taxon*", "include_global_state":false}'
+      # - name: Clean taxdump folder and delete indices and snapshots for that release
+      #   run: |
+      #     mkdir -p resources/taxdump
+      #     rm -rf resources/taxdump/*
+      #     curl -s -X DELETE "es1:9200/*"
+      #     curl -s -X DELETE "es1:9200/_snapshot/dev/*"
+      # - name: Run genomehubs init
+      #   run: |
+      #     docker run --rm --network=host \
+      #       -v `pwd`/sources:/genomehubs/sources \
+      #       -v /volumes/docker/resources:/genomehubs/resources \
+      #       genomehubs/genomehubs:develop bash -c \
+      #         "genomehubs init \
+      #           --es-host http://es1:9200 \
+      #           --taxonomy-source ncbi \
+      #           --config-file sources/goat.yaml \
+      #           --taxonomy-jsonl sources/ena-taxonomy/ena-taxonomy.extra.jsonl.gz \
+      #           --taxonomy-ncbi-root 2759 \
+      #           --taxon-preload"
+      # - name: Run docker genomehubs index --assembly-data
+      #   run: |
+      #     docker run --rm --network=host \
+      #       -v `pwd`/sources:/genomehubs/sources \
+      #       genomehubs/genomehubs:develop bash -c \
+      #         "genomehubs index \
+      #           --es-host http://es1:9200 \
+      #           --taxonomy-source ncbi \
+      #           --config-file sources/goat.yaml \
+      #           --assembly-dir sources/assembly-data"
+      # - name: Snapshot initassembly
+      #   run: |
+      #     curl -s -X DELETE "es1:9200/_snapshot/dev/${RELEASE}_initassembly" || exit 0
+      #     curl -s -X PUT    "es1:9200/_snapshot/dev/${RELEASE}_initassembly?wait_for_completion=true&pretty" \
+      #       -H 'Content-Type: application/json' \
+      #       -d' { "indices": "assembly*,attributes*,feature*,identifiers*,taxon*", "include_global_state":false}'
 
   genomehubs_index_attributes:
     needs:
       - get_dockers
       - genomehubs_init
-    runs-on:  self-hosted
+    runs-on:  [ self-hosted, runner1 ]
   
     steps:
       - name: Get bash release name
@@ -322,7 +322,7 @@ jobs:
     needs:
       - get_dockers
       - genomehubs_index_attributes
-    runs-on:  self-hosted
+    runs-on:  [ self-hosted, runner2 ]
     steps:
 
       - name: Get bash release name
@@ -363,8 +363,8 @@ jobs:
     needs:
       - get_dockers
       - genomehubs_index_attributes
-    runs-on:  self-hosted
-    steps:
+    runs-on:  [ self-hosted, runner1 ]
+        steps:
 
       - name: Get bash release name
         run:  cat /tmp/CURRENT_RELEASE >> $GITHUB_ENV
